name: ci-build
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: build-and-testing
    steps:
      - uses: actions/checkout@v1
      - name: install-java8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: temurin
          cache: maven
      - name: build-project
        run: ./mvnw clean verify
